version: '3'

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.18
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./forgejo-data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    restart: unless-stopped