name: Collect Commits
on:
  push:

jobs:
  collect-commits:
    runs-on: [self-hosted, mse] 
    steps:
      - name: Collect info
        run: |
          cd /data/
          mkdir -p '${{github.repository}}'

          cat > ./run.json <<EOF 
          ${{ toJson(github) }}
          EOF

          python3 get_info.py
