name: Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install black, flake8
      run: |
        pip install flake8, black

    - name: Run black
      run: black . --check -S

    - name: Run flake8
      run: flake8 .
