name: Main Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test list file
        run: echo "isaacs/github" > test_list.txt

      - name: Run main.py and save output (commits)
        run: python main.py --commits -l test_list.txt -o output_commits.csv -t ${{ secrets.GITHUB_TOKEN }}
      - name: Compare output with reference CSV (commits)
        run: |
          if [ ! -f output_commits.csv ]; then
            echo 'output_commits.csv not found, skipping compare.'
            exit 1
          fi
          python compare_csv.py output_commits.csv .github/workflows/reference_commits.csv

      - name: Run main.py and save output (contributors)
        run: python main.py --contributors -l test_list.txt -o output_contributors.csv -t ${{ secrets.GITHUB_TOKEN }}
      - name: Compare output with reference CSV (contributors)
        run: |
          if [ ! -f output_contributors.csv ]; then
            echo 'output_contributors.csv not found, skipping compare.'
            exit 1
          fi
          python compare_csv.py output_contributors.csv .github/workflows/reference_contributors.csv

      - name: Run main.py and save output (issues)
        run: python main.py --issues -l test_list.txt -o output_issues.csv -t ${{ secrets.GITHUB_TOKEN }}
      - name: Compare output with reference CSV (issues)
        run: |
          if [ ! -f output_issues.csv ]; then
            echo 'output_issues.csv not found, skipping compare.'
            exit 1
          fi
          python compare_csv.py output_issues.csv .github/workflows/reference_issues.csv

      - name: Run main.py and save output (pulls)
        run: python main.py -p -l test_list.txt -o output_pulls.csv -t ${{ secrets.GITHUB_TOKEN }}
      - name: Compare output with reference CSV (pulls)
        run: |
          if [ ! -f output_pulls.csv ]; then
            echo 'output_pulls.csv not found, skipping compare.'
            exit 1
          fi
          python compare_csv.py output_pulls.csv .github/workflows/reference_pulls.csv

